const { sequelize, User, JobQuote, Material, CodeCompliance, Schedule, Invoice, Technician, Customer, Project, Expense, Warranty, Equipment, ServiceContract, Permit, Supplier } = require('../models');
const bcrypt = require('bcryptjs');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database synced. Seeding data...');

    const hashedPassword = await bcrypt.hash('password123', 10);
    const user = await User.create({
      name: 'John Contractor', email: 'demo@hvacpro.com', password: hashedPassword,
      company: 'ProTrades HVAC & Plumbing', role: 'contractor'
    });
    const uid = user.id;

    // 1. JOB QUOTES (15)
    await JobQuote.bulkCreate([
      { title: 'Water Heater Replacement', description: 'Replace 50-gallon gas water heater in basement. Current unit is 15 years old with visible corrosion.', jobType: 'Plumbing', customerName: 'Sarah Johnson', customerPhone: '555-0101', customerEmail: 'sarah@email.com', address: '123 Oak Street, Springfield, IL', estimatedCost: 2800, laborHours: 6, status: 'pending', priority: 'high', user_id: uid },
      { title: 'Full HVAC System Install', description: 'New construction 2500 sq ft home needs complete HVAC system with 3-ton heat pump and ductwork.', jobType: 'HVAC', customerName: 'Mike Williams', customerPhone: '555-0102', customerEmail: 'mike@email.com', address: '456 Maple Ave', estimatedCost: 12500, laborHours: 32, status: 'approved', priority: 'high', user_id: uid },
      { title: 'Electrical Panel Upgrade', description: 'Upgrade from 100A to 200A electrical panel. Home built in 1975, needs modern breakers.', jobType: 'Electrical', customerName: 'Lisa Chen', customerPhone: '555-0103', customerEmail: 'lisa@email.com', address: '789 Elm Drive', estimatedCost: 3500, laborHours: 8, status: 'pending', priority: 'medium', user_id: uid },
      { title: 'Kitchen Plumbing Remodel', description: 'Complete kitchen plumbing remodel including new sink, dishwasher connection, garbage disposal.', jobType: 'Plumbing', customerName: 'David Brown', customerPhone: '555-0104', customerEmail: 'david@email.com', address: '321 Pine Road', estimatedCost: 4200, laborHours: 12, status: 'in_progress', priority: 'medium', user_id: uid },
      { title: 'AC Unit Repair', description: 'Central AC not cooling. Possible refrigerant leak. Carrier 3.5 ton unit blowing warm air.', jobType: 'HVAC', customerName: 'Jennifer Davis', customerPhone: '555-0105', customerEmail: 'jen@email.com', address: '654 Cedar Lane', estimatedCost: 850, laborHours: 3, status: 'pending', priority: 'high', user_id: uid },
      { title: 'Bathroom Exhaust Fan Install', description: 'Install bathroom exhaust fan with humidity sensor. No existing ventilation.', jobType: 'HVAC', customerName: 'Robert Taylor', customerPhone: '555-0106', customerEmail: 'rob@email.com', address: '987 Birch Court', estimatedCost: 650, laborHours: 4, status: 'completed', priority: 'low', user_id: uid },
      { title: 'Whole House Rewiring', description: 'Complete rewiring of 1960s ranch home. Replace all knob-and-tube with Romex.', jobType: 'Electrical', customerName: 'Amanda Wilson', customerPhone: '555-0107', customerEmail: 'amanda@email.com', address: '147 Willow Way', estimatedCost: 15000, laborHours: 48, status: 'approved', priority: 'high', user_id: uid },
      { title: 'Sewer Line Repair', description: 'Tree root intrusion in main sewer line. 30 feet of clay pipe needs replacement.', jobType: 'Plumbing', customerName: 'Thomas Anderson', customerPhone: '555-0108', customerEmail: 'tom@email.com', address: '258 Ash Boulevard', estimatedCost: 5500, laborHours: 16, status: 'pending', priority: 'high', user_id: uid },
      { title: 'Mini Split Installation', description: 'Install ductless mini-split in converted garage workshop. 500 sq ft space.', jobType: 'HVAC', customerName: 'Karen Martinez', customerPhone: '555-0109', customerEmail: 'karen@email.com', address: '369 Poplar Place', estimatedCost: 3800, laborHours: 8, status: 'approved', priority: 'medium', user_id: uid },
      { title: 'Outdoor Lighting Installation', description: 'Landscape lighting system: 12 path lights, 4 spot lights, 2 wall wash lights.', jobType: 'Electrical', customerName: 'Steve Robinson', customerPhone: '555-0110', customerEmail: 'steve@email.com', address: '741 Magnolia Drive', estimatedCost: 2200, laborHours: 10, status: 'pending', priority: 'low', user_id: uid },
      { title: 'Gas Line Installation', description: 'Run new gas line from meter to outdoor kitchen. 60 feet of line.', jobType: 'Plumbing', customerName: 'Nancy Lee', customerPhone: '555-0111', customerEmail: 'nancy@email.com', address: '852 Walnut Circle', estimatedCost: 1800, laborHours: 6, status: 'pending', priority: 'medium', user_id: uid },
      { title: 'EV Charger Installation', description: 'Install Level 2 EV charger (240V/50A) in garage with dedicated circuit.', jobType: 'Electrical', customerName: 'James Kim', customerPhone: '555-0112', customerEmail: 'james@email.com', address: '963 Hickory Street', estimatedCost: 1500, laborHours: 5, status: 'approved', priority: 'medium', user_id: uid },
      { title: 'Furnace Replacement', description: 'Replace 20-year-old gas furnace with high-efficiency condensing unit.', jobType: 'HVAC', customerName: 'Patricia Moore', customerPhone: '555-0113', customerEmail: 'pat@email.com', address: '174 Spruce Ave', estimatedCost: 5500, laborHours: 10, status: 'pending', priority: 'high', user_id: uid },
      { title: 'Sump Pump Installation', description: 'Install primary sump pump with battery backup. Basement floods during heavy rain.', jobType: 'Plumbing', customerName: 'Richard White', customerPhone: '555-0114', customerEmail: 'rich@email.com', address: '285 Cherry Lane', estimatedCost: 1900, laborHours: 6, status: 'pending', priority: 'high', user_id: uid },
      { title: 'Commercial Kitchen Ventilation', description: 'Install Type I hood system for restaurant kitchen with fire suppression and makeup air.', jobType: 'HVAC', customerName: 'Maria Garcia', customerPhone: '555-0115', customerEmail: 'maria@email.com', address: '396 Main Street', estimatedCost: 18000, laborHours: 40, status: 'approved', priority: 'high', user_id: uid },
    ]);
    console.log('  ✓ 15 Job Quotes seeded');

    // 2. MATERIALS (15)
    await Material.bulkCreate([
      { name: '3/4" Copper Pipe (Type L)', category: 'Plumbing', description: 'Hard copper tubing for water supply', unit: 'linear ft', unitPrice: 4.25, quantity: 500, supplier: 'Ferguson Supply', sku: 'COP-075-L', inStock: true, minOrderQty: 10, leadTimeDays: 1, user_id: uid },
      { name: '12/2 Romex NM-B Wire', category: 'Electrical', description: 'Non-metallic sheathed cable for 20A circuits', unit: 'roll (250ft)', unitPrice: 89.99, quantity: 25, supplier: 'Graybar Electric', sku: 'ROM-122-250', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: '3-Ton Heat Pump Unit', category: 'HVAC', description: 'Carrier 14 SEER2 heat pump condensing unit', unit: 'unit', unitPrice: 3200.00, quantity: 3, supplier: 'Carrier Wholesale', sku: 'CAR-HP3T-14S', inStock: true, minOrderQty: 1, leadTimeDays: 5, user_id: uid },
      { name: '50-Gal Gas Water Heater', category: 'Plumbing', description: 'A.O. Smith ProLine gas water heater', unit: 'unit', unitPrice: 649.99, quantity: 8, supplier: 'Ferguson Supply', sku: 'AOS-50G-40K', inStock: true, minOrderQty: 1, leadTimeDays: 2, user_id: uid },
      { name: '200A Main Breaker Panel', category: 'Electrical', description: 'Square D Homeline 200A 40-space panel', unit: 'unit', unitPrice: 189.99, quantity: 12, supplier: 'Graybar Electric', sku: 'SQD-HL200-40', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: '6" Flexible Ductwork', category: 'HVAC', description: 'Insulated flexible duct, R-8 value', unit: 'roll (25ft)', unitPrice: 42.50, quantity: 40, supplier: 'HVAC Direct', sku: 'FLX-6R8-25', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: 'PVC Schedule 40 Pipe 4"', category: 'Plumbing', description: 'PVC drain/waste/vent pipe', unit: 'stick (10ft)', unitPrice: 12.99, quantity: 100, supplier: 'Ferguson Supply', sku: 'PVC-040-4', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: '20A GFCI Receptacle', category: 'Electrical', description: 'Leviton SmartlockPro GFCI outlet', unit: 'each', unitPrice: 18.99, quantity: 200, supplier: 'Graybar Electric', sku: 'LEV-GFCI-20W', inStock: true, minOrderQty: 5, leadTimeDays: 1, user_id: uid },
      { name: 'Programmable Thermostat', category: 'HVAC', description: 'Honeywell T6 Pro programmable', unit: 'each', unitPrice: 89.00, quantity: 30, supplier: 'HVAC Direct', sku: 'HON-T6PRO', inStock: true, minOrderQty: 1, leadTimeDays: 2, user_id: uid },
      { name: 'SharkBite Push-to-Connect 3/4"', category: 'Plumbing', description: 'Push-fit coupling for copper/PEX/CPVC', unit: 'each', unitPrice: 8.75, quantity: 150, supplier: 'Ferguson Supply', sku: 'SHB-075-CPL', inStock: true, minOrderQty: 5, leadTimeDays: 1, user_id: uid },
      { name: '14/3 MC Cable', category: 'Electrical', description: 'Metal-clad cable for commercial', unit: 'roll (250ft)', unitPrice: 165.00, quantity: 15, supplier: 'Graybar Electric', sku: 'MC-143-250', inStock: false, minOrderQty: 1, leadTimeDays: 5, user_id: uid },
      { name: 'R-410A Refrigerant', category: 'HVAC', description: 'Puron refrigerant for modern AC', unit: 'cylinder (25lb)', unitPrice: 175.00, quantity: 20, supplier: 'HVAC Direct', sku: 'R410A-25', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: '1/2" PEX Tubing (Red)', category: 'Plumbing', description: 'CrossLinked polyethylene for hot water', unit: 'roll (100ft)', unitPrice: 35.99, quantity: 60, supplier: 'Ferguson Supply', sku: 'PEX-050-R100', inStock: true, minOrderQty: 1, leadTimeDays: 1, user_id: uid },
      { name: 'LED Recessed Light 6"', category: 'Electrical', description: 'Halo 6-inch IC-rated LED retrofit', unit: 'each', unitPrice: 12.50, quantity: 300, supplier: 'Graybar Electric', sku: 'HAL-6LED-IC', inStock: true, minOrderQty: 6, leadTimeDays: 1, user_id: uid },
      { name: 'Condensate Pump', category: 'HVAC', description: 'Little Giant VCMA-20 condensate removal pump', unit: 'each', unitPrice: 62.00, quantity: 15, supplier: 'HVAC Direct', sku: 'LG-VCMA20', inStock: true, minOrderQty: 1, leadTimeDays: 2, user_id: uid },
    ]);
    console.log('  ✓ 15 Materials seeded');

    // 3. CODE COMPLIANCE (15)
    await CodeCompliance.bulkCreate([
      { title: 'Water Heater TPR Valve', codeReference: 'IPC 504.6', category: 'Plumbing', description: 'TPR valve requirements for water heaters', jurisdiction: 'Illinois', requirements: 'TPR valve must discharge to within 6 inches of floor or to exterior.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Stop work order, $500 fine', inspectionRequired: true, notes: 'Common violation: TPR discharge piped upward', user_id: uid },
      { title: 'GFCI Protection Requirements', codeReference: 'NEC 210.8', category: 'Electrical', description: 'GFCI protection for dwelling units', jurisdiction: 'Illinois', requirements: 'GFCI required in bathrooms, kitchens, garages, outdoors, crawl spaces.', status: 'active', effectiveDate: '2023-01-01', penalties: '$750 fine', inspectionRequired: true, notes: 'NEC 2023 expanded requirements', user_id: uid },
      { title: 'HVAC Duct Insulation', codeReference: 'IMC 603.8', category: 'HVAC', description: 'Minimum insulation for supply ducts', jurisdiction: 'Illinois', requirements: 'Supply ducts in unconditioned spaces: minimum R-8 insulation.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Failed inspection', inspectionRequired: true, notes: 'Energy code may require higher R-values', user_id: uid },
      { title: 'Drain Pipe Slope', codeReference: 'IPC 704.1', category: 'Plumbing', description: 'Minimum slope for horizontal drainage piping', jurisdiction: 'Illinois', requirements: 'Pipes ≤3": 1/4" per foot. Pipes ≥4": 1/8" per foot.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Re-work required', inspectionRequired: true, notes: 'Grade must be uniform', user_id: uid },
      { title: 'AFCI Protection', codeReference: 'NEC 210.12', category: 'Electrical', description: 'Arc-fault circuit interrupter requirements', jurisdiction: 'Illinois', requirements: 'AFCI required for all 120V 15A and 20A branch circuits in living spaces.', status: 'active', effectiveDate: '2023-01-01', penalties: '$500 fine per circuit', inspectionRequired: true, notes: 'Dual-function breakers available', user_id: uid },
      { title: 'Refrigerant Line Protection', codeReference: 'IMC 1105.7', category: 'HVAC', description: 'Protection for refrigerant piping', jurisdiction: 'Illinois', requirements: 'UV-resistant insulation required outdoors. Support every 8ft horizontal.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Correction required', inspectionRequired: true, notes: 'Check local amendments', user_id: uid },
      { title: 'Backflow Prevention', codeReference: 'IPC 608.1', category: 'Plumbing', description: 'Cross-connection control and backflow prevention', jurisdiction: 'Illinois', requirements: 'Approved backflow preventers required based on hazard level.', status: 'active', effectiveDate: '2024-01-01', penalties: '$1000 fine, disconnection possible', inspectionRequired: true, notes: 'Annual testing required', user_id: uid },
      { title: 'Service Entrance', codeReference: 'NEC 230.70', category: 'Electrical', description: 'Service disconnecting means requirements', jurisdiction: 'Illinois', requirements: 'Service disconnect at readily accessible location. Max 6 disconnects.', status: 'active', effectiveDate: '2023-01-01', penalties: 'Stop work, $1000 fine', inspectionRequired: true, notes: 'NEC 2023 requires emergency disconnect outside', user_id: uid },
      { title: 'Combustion Air', codeReference: 'IMC 701.1', category: 'HVAC', description: 'Air supply for fuel-burning appliances', jurisdiction: 'Illinois', requirements: 'Two openings required in confined spaces with fuel-burning appliances.', status: 'active', effectiveDate: '2024-01-01', penalties: 'CO hazard, immediate stop work', inspectionRequired: true, notes: 'Direct vent appliances exempt', user_id: uid },
      { title: 'Fixture Unit Calculations', codeReference: 'IPC 709.1', category: 'Plumbing', description: 'Drainage fixture unit values and pipe sizing', jurisdiction: 'Illinois', requirements: '3-inch pipe: max 35 DFU. 4-inch pipe: max 216 DFU.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Redesign required', inspectionRequired: true, notes: 'Building drain sizing considers slope', user_id: uid },
      { title: 'Electrical Box Fill', codeReference: 'NEC 314.16', category: 'Electrical', description: 'Maximum conductor fill for outlet boxes', jurisdiction: 'Illinois', requirements: '#14 wire = 2 cu in, #12 wire = 2.25 cu in per conductor.', status: 'active', effectiveDate: '2023-01-01', penalties: 'Fire hazard citation', inspectionRequired: true, notes: 'Overfilled boxes common violation', user_id: uid },
      { title: 'Duct Smoke Detectors', codeReference: 'IMC 606.4', category: 'HVAC', description: 'Smoke detector requirements in HVAC systems', jurisdiction: 'Illinois', requirements: 'Required in systems >2000 CFM. Must shut down air handler.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Fire code violation, $2000 fine', inspectionRequired: true, notes: 'Residential typically exempt', user_id: uid },
      { title: 'Water Pipe Sizing', codeReference: 'IPC 604.3', category: 'Plumbing', description: 'Minimum pipe sizes for water distribution', jurisdiction: 'Illinois', requirements: 'Main service: minimum 3/4 inch. Velocity ≤8 fps.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Redesign required', inspectionRequired: true, notes: 'Low pressure areas may need larger pipes', user_id: uid },
      { title: 'Grounding Electrode System', codeReference: 'NEC 250.50', category: 'Electrical', description: 'Grounding electrode requirements', jurisdiction: 'Illinois', requirements: 'All available electrodes must be bonded together.', status: 'active', effectiveDate: '2023-01-01', penalties: 'Safety hazard, immediate correction', inspectionRequired: true, notes: 'Water pipe alone no longer sufficient', user_id: uid },
      { title: 'Equipment Clearance', codeReference: 'IMC 306.3', category: 'HVAC', description: 'Minimum clearance around mechanical equipment', jurisdiction: 'Illinois', requirements: 'Min 30 inches working space in front of service access.', status: 'active', effectiveDate: '2024-01-01', penalties: 'Failed inspection', inspectionRequired: true, notes: 'Check manufacturer specs', user_id: uid },
    ]);
    console.log('  ✓ 15 Code Compliance records seeded');

    // 4. SCHEDULES (15)
    await Schedule.bulkCreate([
      { title: 'Water Heater - Johnson', description: 'Replace 50-gal gas water heater', jobType: 'Plumbing', customerName: 'Sarah Johnson', customerPhone: '555-0101', address: '123 Oak Street', technicianName: 'Mike Torres', scheduledDate: '2026-03-20', startTime: '08:00', endTime: '14:00', status: 'scheduled', priority: 'high', estimatedDuration: 6, notes: 'Customer has dog', user_id: uid },
      { title: 'HVAC Install - Williams', description: 'Full HVAC system day 1', jobType: 'HVAC', customerName: 'Mike Williams', customerPhone: '555-0102', address: '456 Maple Ave', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-20', startTime: '07:00', endTime: '17:00', status: 'scheduled', priority: 'high', estimatedDuration: 10, notes: 'Day 1 of 4', user_id: uid },
      { title: 'Panel Upgrade - Chen', description: '200A panel upgrade', jobType: 'Electrical', customerName: 'Lisa Chen', customerPhone: '555-0103', address: '789 Elm Drive', technicianName: 'Dave Sparks', scheduledDate: '2026-03-21', startTime: '08:00', endTime: '16:00', status: 'scheduled', priority: 'medium', estimatedDuration: 8, notes: 'Power company disconnect at 8AM', user_id: uid },
      { title: 'Kitchen Plumbing - Brown', description: 'Sink and dishwasher hookup', jobType: 'Plumbing', customerName: 'David Brown', customerPhone: '555-0104', address: '321 Pine Road', technicianName: 'Mike Torres', scheduledDate: '2026-03-21', startTime: '09:00', endTime: '15:00', status: 'scheduled', priority: 'medium', estimatedDuration: 6, user_id: uid },
      { title: 'AC Repair - Davis', description: 'Diagnose and repair AC', jobType: 'HVAC', customerName: 'Jennifer Davis', customerPhone: '555-0105', address: '654 Cedar Lane', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-22', startTime: '08:00', endTime: '11:00', status: 'scheduled', priority: 'high', estimatedDuration: 3, user_id: uid },
      { title: 'Exhaust Fan - Taylor', description: 'Bathroom exhaust fan install', jobType: 'HVAC', customerName: 'Robert Taylor', customerPhone: '555-0106', address: '987 Birch Court', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-22', startTime: '13:00', endTime: '17:00', status: 'scheduled', priority: 'low', estimatedDuration: 4, user_id: uid },
      { title: 'Rewiring - Wilson', description: 'Whole house rewiring day 1', jobType: 'Electrical', customerName: 'Amanda Wilson', customerPhone: '555-0107', address: '147 Willow Way', technicianName: 'Dave Sparks', scheduledDate: '2026-03-23', startTime: '07:00', endTime: '17:00', status: 'scheduled', priority: 'high', estimatedDuration: 10, user_id: uid },
      { title: 'Sewer Repair - Anderson', description: 'Main sewer line replacement', jobType: 'Plumbing', customerName: 'Thomas Anderson', customerPhone: '555-0108', address: '258 Ash Blvd', technicianName: 'Mike Torres', scheduledDate: '2026-03-23', startTime: '07:00', endTime: '17:00', status: 'scheduled', priority: 'high', estimatedDuration: 10, user_id: uid },
      { title: 'Mini Split - Martinez', description: 'Ductless mini-split install', jobType: 'HVAC', customerName: 'Karen Martinez', customerPhone: '555-0109', address: '369 Poplar Place', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-24', startTime: '08:00', endTime: '16:00', status: 'scheduled', priority: 'medium', estimatedDuration: 8, user_id: uid },
      { title: 'Lighting - Robinson', description: 'Landscape LED lighting', jobType: 'Electrical', customerName: 'Steve Robinson', customerPhone: '555-0110', address: '741 Magnolia Dr', technicianName: 'Dave Sparks', scheduledDate: '2026-03-24', startTime: '08:00', endTime: '18:00', status: 'scheduled', priority: 'low', estimatedDuration: 10, user_id: uid },
      { title: 'Gas Line - Lee', description: 'Gas line to outdoor kitchen', jobType: 'Plumbing', customerName: 'Nancy Lee', customerPhone: '555-0111', address: '852 Walnut Circle', technicianName: 'Mike Torres', scheduledDate: '2026-03-25', startTime: '08:00', endTime: '14:00', status: 'scheduled', priority: 'medium', estimatedDuration: 6, user_id: uid },
      { title: 'EV Charger - Kim', description: 'Level 2 EV charger install', jobType: 'Electrical', customerName: 'James Kim', customerPhone: '555-0112', address: '963 Hickory St', technicianName: 'Dave Sparks', scheduledDate: '2026-03-25', startTime: '09:00', endTime: '14:00', status: 'scheduled', priority: 'medium', estimatedDuration: 5, user_id: uid },
      { title: 'Furnace - Moore', description: 'Gas furnace replacement', jobType: 'HVAC', customerName: 'Patricia Moore', customerPhone: '555-0113', address: '174 Spruce Ave', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-26', startTime: '08:00', endTime: '18:00', status: 'scheduled', priority: 'high', estimatedDuration: 10, user_id: uid },
      { title: 'Sump Pump - White', description: 'Sump pump with backup', jobType: 'Plumbing', customerName: 'Richard White', customerPhone: '555-0114', address: '285 Cherry Lane', technicianName: 'Mike Torres', scheduledDate: '2026-03-26', startTime: '08:00', endTime: '14:00', status: 'scheduled', priority: 'high', estimatedDuration: 6, user_id: uid },
      { title: 'Commercial Hood - Garcia', description: 'Restaurant kitchen ventilation', jobType: 'HVAC', customerName: 'Maria Garcia', customerPhone: '555-0115', address: '396 Main Street', technicianName: 'Carlos Ruiz', scheduledDate: '2026-03-27', startTime: '06:00', endTime: '18:00', status: 'scheduled', priority: 'high', estimatedDuration: 12, user_id: uid },
    ]);
    console.log('  ✓ 15 Schedules seeded');

    // 5. INVOICES (15)
    await Invoice.bulkCreate([
      { invoiceNumber: 'INV-2026-001', customerName: 'Sarah Johnson', customerEmail: 'sarah@email.com', customerPhone: '555-0101', customerAddress: '123 Oak Street', jobDescription: 'Water heater replacement', laborCost: 900, materialCost: 1200, taxRate: 8.5, taxAmount: 178.50, totalAmount: 2278.50, status: 'sent', dueDate: '2026-04-01', user_id: uid },
      { invoiceNumber: 'INV-2026-002', customerName: 'Mike Williams', customerEmail: 'mike@email.com', customerPhone: '555-0102', customerAddress: '456 Maple Ave', jobDescription: 'Complete HVAC system installation', laborCost: 4800, materialCost: 6500, taxRate: 8.5, taxAmount: 960.50, totalAmount: 12260.50, status: 'draft', dueDate: '2026-04-15', user_id: uid },
      { invoiceNumber: 'INV-2026-003', customerName: 'Lisa Chen', customerEmail: 'lisa@email.com', customerPhone: '555-0103', customerAddress: '789 Elm Drive', jobDescription: '200A panel upgrade with surge protector', laborCost: 1200, materialCost: 850, taxRate: 8.5, taxAmount: 174.25, totalAmount: 2224.25, status: 'sent', dueDate: '2026-03-30', user_id: uid },
      { invoiceNumber: 'INV-2026-004', customerName: 'David Brown', customerEmail: 'david@email.com', customerPhone: '555-0104', customerAddress: '321 Pine Road', jobDescription: 'Kitchen plumbing remodel', laborCost: 1800, materialCost: 1400, taxRate: 8.5, taxAmount: 272.00, totalAmount: 3472.00, status: 'paid', dueDate: '2026-03-15', paidDate: '2026-03-14', user_id: uid },
      { invoiceNumber: 'INV-2026-005', customerName: 'Jennifer Davis', customerEmail: 'jen@email.com', customerPhone: '555-0105', customerAddress: '654 Cedar Lane', jobDescription: 'AC diagnostics and refrigerant recharge', laborCost: 250, materialCost: 380, taxRate: 8.5, taxAmount: 53.55, totalAmount: 683.55, status: 'sent', dueDate: '2026-04-05', user_id: uid },
      { invoiceNumber: 'INV-2026-006', customerName: 'Robert Taylor', customerEmail: 'rob@email.com', customerPhone: '555-0106', customerAddress: '987 Birch Court', jobDescription: 'Bathroom exhaust fan installation', laborCost: 350, materialCost: 220, taxRate: 8.5, taxAmount: 48.45, totalAmount: 618.45, status: 'paid', dueDate: '2026-03-10', paidDate: '2026-03-08', user_id: uid },
      { invoiceNumber: 'INV-2026-007', customerName: 'Amanda Wilson', customerEmail: 'amanda@email.com', customerPhone: '555-0107', customerAddress: '147 Willow Way', jobDescription: 'Complete house rewiring', laborCost: 7200, materialCost: 4800, taxRate: 8.5, taxAmount: 1020.00, totalAmount: 13020.00, status: 'draft', dueDate: '2026-04-30', user_id: uid },
      { invoiceNumber: 'INV-2026-008', customerName: 'Thomas Anderson', customerEmail: 'tom@email.com', customerPhone: '555-0108', customerAddress: '258 Ash Blvd', jobDescription: 'Main sewer line replacement', laborCost: 2400, materialCost: 1800, taxRate: 8.5, taxAmount: 357.00, totalAmount: 4557.00, status: 'sent', dueDate: '2026-04-10', user_id: uid },
      { invoiceNumber: 'INV-2026-009', customerName: 'Karen Martinez', customerEmail: 'karen@email.com', customerPhone: '555-0109', customerAddress: '369 Poplar Place', jobDescription: 'Ductless mini-split installation', laborCost: 1200, materialCost: 2100, taxRate: 8.5, taxAmount: 280.50, totalAmount: 3580.50, status: 'draft', dueDate: '2026-04-15', user_id: uid },
      { invoiceNumber: 'INV-2026-010', customerName: 'Steve Robinson', customerEmail: 'steve@email.com', customerPhone: '555-0110', customerAddress: '741 Magnolia Dr', jobDescription: 'Landscape LED lighting system', laborCost: 1500, materialCost: 900, taxRate: 8.5, taxAmount: 204.00, totalAmount: 2604.00, status: 'sent', dueDate: '2026-04-20', user_id: uid },
      { invoiceNumber: 'INV-2026-011', customerName: 'Nancy Lee', customerEmail: 'nancy@email.com', customerPhone: '555-0111', customerAddress: '852 Walnut Circle', jobDescription: 'Gas line to outdoor kitchen', laborCost: 800, materialCost: 650, taxRate: 8.5, taxAmount: 123.25, totalAmount: 1573.25, status: 'overdue', dueDate: '2026-03-01', user_id: uid },
      { invoiceNumber: 'INV-2026-012', customerName: 'James Kim', customerEmail: 'james@email.com', customerPhone: '555-0112', customerAddress: '963 Hickory St', jobDescription: 'Level 2 EV charger installation', laborCost: 600, materialCost: 450, taxRate: 8.5, taxAmount: 89.25, totalAmount: 1139.25, status: 'paid', dueDate: '2026-03-20', paidDate: '2026-03-18', user_id: uid },
      { invoiceNumber: 'INV-2026-013', customerName: 'Patricia Moore', customerEmail: 'pat@email.com', customerPhone: '555-0113', customerAddress: '174 Spruce Ave', jobDescription: 'High-efficiency furnace replacement', laborCost: 1800, materialCost: 3200, taxRate: 8.5, taxAmount: 425.00, totalAmount: 5425.00, status: 'draft', dueDate: '2026-04-15', user_id: uid },
      { invoiceNumber: 'INV-2026-014', customerName: 'Richard White', customerEmail: 'rich@email.com', customerPhone: '555-0114', customerAddress: '285 Cherry Lane', jobDescription: 'Sump pump system with backup', laborCost: 700, materialCost: 850, taxRate: 8.5, taxAmount: 131.75, totalAmount: 1681.75, status: 'sent', dueDate: '2026-04-05', user_id: uid },
      { invoiceNumber: 'INV-2026-015', customerName: 'Maria Garcia', customerEmail: 'maria@email.com', customerPhone: '555-0115', customerAddress: '396 Main Street', jobDescription: 'Commercial kitchen hood with fire suppression', laborCost: 6000, materialCost: 10000, taxRate: 8.5, taxAmount: 1360.00, totalAmount: 17360.00, status: 'draft', dueDate: '2026-05-01', user_id: uid },
    ]);
    console.log('  ✓ 15 Invoices seeded');

    // 6. CUSTOMERS (15)
    await Customer.bulkCreate([
      { name: 'Sarah Johnson', email: 'sarah@email.com', phone: '555-0101', address: '123 Oak Street', city: 'Springfield', state: 'IL', zipCode: '62701', propertyType: 'residential', preferredContact: 'phone', totalSpent: 2278.50, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Mike Williams', email: 'mike@email.com', phone: '555-0102', address: '456 Maple Ave', city: 'Springfield', state: 'IL', zipCode: '62702', propertyType: 'residential', preferredContact: 'email', totalSpent: 12260.50, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Lisa Chen', email: 'lisa@email.com', phone: '555-0103', address: '789 Elm Drive', city: 'Springfield', state: 'IL', zipCode: '62703', propertyType: 'residential', preferredContact: 'phone', totalSpent: 2224.25, jobCount: 1, rating: 4, user_id: uid },
      { name: 'David Brown', email: 'david@email.com', phone: '555-0104', address: '321 Pine Road', city: 'Springfield', state: 'IL', zipCode: '62704', propertyType: 'residential', preferredContact: 'email', totalSpent: 3472.00, jobCount: 2, rating: 5, user_id: uid },
      { name: 'Jennifer Davis', email: 'jen@email.com', phone: '555-0105', address: '654 Cedar Lane', city: 'Springfield', state: 'IL', zipCode: '62705', propertyType: 'residential', preferredContact: 'phone', totalSpent: 683.55, jobCount: 1, rating: 4, user_id: uid },
      { name: 'Robert Taylor', email: 'rob@email.com', phone: '555-0106', address: '987 Birch Court', city: 'Springfield', state: 'IL', zipCode: '62706', propertyType: 'residential', preferredContact: 'phone', totalSpent: 618.45, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Amanda Wilson', email: 'amanda@email.com', phone: '555-0107', address: '147 Willow Way', city: 'Springfield', state: 'IL', zipCode: '62707', propertyType: 'residential', preferredContact: 'email', totalSpent: 13020.00, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Thomas Anderson', email: 'tom@email.com', phone: '555-0108', address: '258 Ash Blvd', city: 'Springfield', state: 'IL', zipCode: '62708', propertyType: 'residential', preferredContact: 'phone', totalSpent: 4557.00, jobCount: 1, rating: 4, user_id: uid },
      { name: 'Karen Martinez', email: 'karen@email.com', phone: '555-0109', address: '369 Poplar Place', city: 'Springfield', state: 'IL', zipCode: '62709', propertyType: 'residential', preferredContact: 'email', totalSpent: 3580.50, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Steve Robinson', email: 'steve@email.com', phone: '555-0110', address: '741 Magnolia Dr', city: 'Springfield', state: 'IL', zipCode: '62710', propertyType: 'residential', preferredContact: 'phone', totalSpent: 2604.00, jobCount: 1, rating: 3, user_id: uid },
      { name: 'Nancy Lee', email: 'nancy@email.com', phone: '555-0111', address: '852 Walnut Circle', city: 'Springfield', state: 'IL', zipCode: '62711', propertyType: 'residential', preferredContact: 'email', totalSpent: 1573.25, jobCount: 1, rating: 2, notes: 'Payment overdue - follow up', user_id: uid },
      { name: 'James Kim', email: 'james@email.com', phone: '555-0112', address: '963 Hickory St', city: 'Springfield', state: 'IL', zipCode: '62712', propertyType: 'residential', preferredContact: 'phone', totalSpent: 1139.25, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Patricia Moore', email: 'pat@email.com', phone: '555-0113', address: '174 Spruce Ave', city: 'Springfield', state: 'IL', zipCode: '62713', propertyType: 'residential', preferredContact: 'phone', totalSpent: 5425.00, jobCount: 2, rating: 4, user_id: uid },
      { name: 'Richard White', email: 'rich@email.com', phone: '555-0114', address: '285 Cherry Lane', city: 'Springfield', state: 'IL', zipCode: '62714', propertyType: 'residential', preferredContact: 'email', totalSpent: 1681.75, jobCount: 1, rating: 5, user_id: uid },
      { name: 'Maria Garcia', email: 'maria@email.com', phone: '555-0115', address: '396 Main Street', city: 'Springfield', state: 'IL', zipCode: '62715', propertyType: 'commercial', preferredContact: 'email', totalSpent: 17360.00, jobCount: 1, rating: 5, notes: 'Restaurant owner - large project', user_id: uid },
    ]);
    console.log('  ✓ 15 Customers seeded');

    // 7. TECHNICIANS (15)
    await Technician.bulkCreate([
      { name: 'Mike Torres', email: 'mike.t@protrades.com', phone: '555-2001', specialty: 'Plumbing', certifications: 'Master Plumber License, Backflow Certification', hourlyRate: 65, status: 'active', hireDate: '2019-03-15', address: '100 Worker Lane', rating: 4.8, jobsCompleted: 342, user_id: uid },
      { name: 'Carlos Ruiz', email: 'carlos.r@protrades.com', phone: '555-2002', specialty: 'HVAC', certifications: 'EPA 608 Universal, NATE Certified', hourlyRate: 70, status: 'active', hireDate: '2018-06-01', address: '200 Craft Ave', rating: 4.9, jobsCompleted: 456, user_id: uid },
      { name: 'Dave Sparks', email: 'dave.s@protrades.com', phone: '555-2003', specialty: 'Electrical', certifications: 'Journeyman Electrician, Arc Flash Certified', hourlyRate: 68, status: 'active', hireDate: '2020-01-10', address: '300 Volt Street', rating: 4.7, jobsCompleted: 278, user_id: uid },
      { name: 'Lisa Park', email: 'lisa.p@protrades.com', phone: '555-2004', specialty: 'HVAC', certifications: 'EPA 608, R-410A Certified', hourlyRate: 60, status: 'active', hireDate: '2021-05-20', address: '400 Coil Rd', rating: 4.6, jobsCompleted: 189, user_id: uid },
      { name: 'James Rodriguez', email: 'james.r@protrades.com', phone: '555-2005', specialty: 'Plumbing', certifications: 'Journeyman Plumber, Gas Fitter', hourlyRate: 55, status: 'active', hireDate: '2022-02-14', address: '500 Pipe Way', rating: 4.5, jobsCompleted: 134, user_id: uid },
      { name: 'Sarah Mitchell', email: 'sarah.m@protrades.com', phone: '555-2006', specialty: 'Electrical', certifications: 'Master Electrician, Low Voltage Specialist', hourlyRate: 75, status: 'active', hireDate: '2017-09-01', address: '600 Circuit Blvd', rating: 4.9, jobsCompleted: 520, user_id: uid },
      { name: 'Tom Baker', email: 'tom.b@protrades.com', phone: '555-2007', specialty: 'General', certifications: 'General Contractor License', hourlyRate: 50, status: 'active', hireDate: '2023-01-05', address: '700 Trade Lane', rating: 4.3, jobsCompleted: 87, user_id: uid },
      { name: 'Ana Gonzalez', email: 'ana.g@protrades.com', phone: '555-2008', specialty: 'HVAC', certifications: 'EPA 608, BPI Certified', hourlyRate: 62, status: 'active', hireDate: '2021-11-15', address: '800 Duct Dr', rating: 4.7, jobsCompleted: 203, user_id: uid },
      { name: 'Kevin O\'Brien', email: 'kevin.o@protrades.com', phone: '555-2009', specialty: 'Plumbing', certifications: 'Journeyman Plumber, Medical Gas Installer', hourlyRate: 58, status: 'on_leave', hireDate: '2020-07-20', address: '900 Drain St', rating: 4.4, jobsCompleted: 156, notes: 'On medical leave until April', user_id: uid },
      { name: 'Rachel Kim', email: 'rachel.k@protrades.com', phone: '555-2010', specialty: 'Electrical', certifications: 'Apprentice Electrician', hourlyRate: 35, status: 'active', hireDate: '2025-01-15', address: '1000 Amp Ave', rating: 4.2, jobsCompleted: 23, notes: 'New apprentice - needs supervision', user_id: uid },
      { name: 'Marcus Johnson', email: 'marcus.j@protrades.com', phone: '555-2011', specialty: 'HVAC', certifications: 'EPA 608, Commercial Refrigeration', hourlyRate: 72, status: 'active', hireDate: '2018-03-10', address: '1100 Chill Way', rating: 4.8, jobsCompleted: 398, user_id: uid },
      { name: 'Diana Cruz', email: 'diana.c@protrades.com', phone: '555-2012', specialty: 'Plumbing', certifications: 'Master Plumber, Water Treatment Specialist', hourlyRate: 67, status: 'active', hireDate: '2019-08-22', address: '1200 Flow Rd', rating: 4.6, jobsCompleted: 289, user_id: uid },
      { name: 'Ryan Scott', email: 'ryan.s@protrades.com', phone: '555-2013', specialty: 'Electrical', certifications: 'Journeyman Electrician, Solar PV Installer', hourlyRate: 65, status: 'active', hireDate: '2020-11-01', address: '1300 Watt St', rating: 4.5, jobsCompleted: 201, user_id: uid },
      { name: 'Emily Chen', email: 'emily.c@protrades.com', phone: '555-2014', specialty: 'General', certifications: 'Project Management, OSHA 30', hourlyRate: 55, status: 'active', hireDate: '2022-06-15', address: '1400 Build Ave', rating: 4.7, jobsCompleted: 145, notes: 'Great at project coordination', user_id: uid },
      { name: 'Chris Walker', email: 'chris.w@protrades.com', phone: '555-2015', specialty: 'HVAC', certifications: 'EPA 608, Duct Design Certified', hourlyRate: 58, status: 'inactive', hireDate: '2021-04-10', address: '1500 Air Lane', rating: 4.1, jobsCompleted: 167, notes: 'Moved out of state', user_id: uid },
    ]);
    console.log('  ✓ 15 Technicians seeded');

    // 8. PROJECTS (15)
    await Project.bulkCreate([
      { name: 'Johnson Water Heater Project', description: 'Full water heater replacement including disposal of old unit', customerName: 'Sarah Johnson', customerPhone: '555-0101', address: '123 Oak Street', projectType: 'Plumbing', status: 'in_progress', startDate: '2026-03-18', endDate: '2026-03-20', budget: 2800, actualCost: 2100, completionPercent: 75, priority: 'high', assignedTechnician: 'Mike Torres', user_id: uid },
      { name: 'Williams New Construction HVAC', description: 'Complete HVAC for new 2500 sq ft home', customerName: 'Mike Williams', customerPhone: '555-0102', address: '456 Maple Ave', projectType: 'HVAC', status: 'in_progress', startDate: '2026-03-15', endDate: '2026-03-28', budget: 12500, actualCost: 5200, completionPercent: 40, priority: 'high', assignedTechnician: 'Carlos Ruiz', user_id: uid },
      { name: 'Chen Panel Upgrade', description: '200A electrical panel upgrade', customerName: 'Lisa Chen', customerPhone: '555-0103', address: '789 Elm Drive', projectType: 'Electrical', status: 'planning', startDate: '2026-03-21', budget: 3500, completionPercent: 0, priority: 'medium', assignedTechnician: 'Dave Sparks', user_id: uid },
      { name: 'Brown Kitchen Remodel', description: 'Kitchen plumbing overhaul', customerName: 'David Brown', customerPhone: '555-0104', address: '321 Pine Road', projectType: 'Plumbing', status: 'in_progress', startDate: '2026-03-10', endDate: '2026-03-22', budget: 4200, actualCost: 3100, completionPercent: 85, priority: 'medium', assignedTechnician: 'Mike Torres', user_id: uid },
      { name: 'Davis AC Diagnosis', description: 'AC system diagnosis and repair', customerName: 'Jennifer Davis', customerPhone: '555-0105', address: '654 Cedar Lane', projectType: 'HVAC', status: 'planning', startDate: '2026-03-22', budget: 850, completionPercent: 0, priority: 'high', assignedTechnician: 'Carlos Ruiz', user_id: uid },
      { name: 'Wilson Whole House Rewire', description: 'Complete rewiring of 1960s ranch home', customerName: 'Amanda Wilson', customerPhone: '555-0107', address: '147 Willow Way', projectType: 'Electrical', status: 'planning', startDate: '2026-03-23', endDate: '2026-04-05', budget: 15000, completionPercent: 0, priority: 'high', assignedTechnician: 'Dave Sparks', user_id: uid },
      { name: 'Anderson Sewer Replacement', description: 'Main sewer line excavation and replacement', customerName: 'Thomas Anderson', customerPhone: '555-0108', address: '258 Ash Blvd', projectType: 'Plumbing', status: 'planning', startDate: '2026-03-23', budget: 5500, completionPercent: 0, priority: 'high', assignedTechnician: 'Mike Torres', user_id: uid },
      { name: 'Martinez Mini Split', description: 'Garage workshop mini-split system', customerName: 'Karen Martinez', customerPhone: '555-0109', address: '369 Poplar Place', projectType: 'HVAC', status: 'planning', startDate: '2026-03-24', budget: 3800, completionPercent: 0, priority: 'medium', assignedTechnician: 'Carlos Ruiz', user_id: uid },
      { name: 'Robinson Landscape Lighting', description: 'Full landscape LED lighting installation', customerName: 'Steve Robinson', customerPhone: '555-0110', address: '741 Magnolia Dr', projectType: 'Electrical', status: 'planning', startDate: '2026-03-24', budget: 2200, completionPercent: 0, priority: 'low', assignedTechnician: 'Dave Sparks', user_id: uid },
      { name: 'Lee Gas Line Extension', description: 'Gas line to outdoor kitchen area', customerName: 'Nancy Lee', customerPhone: '555-0111', address: '852 Walnut Circle', projectType: 'Plumbing', status: 'on_hold', startDate: '2026-03-25', budget: 1800, completionPercent: 0, priority: 'medium', notes: 'Waiting on customer payment', user_id: uid },
      { name: 'Kim EV Charger Install', description: 'Level 2 EV charger with dedicated circuit', customerName: 'James Kim', customerPhone: '555-0112', address: '963 Hickory St', projectType: 'Electrical', status: 'completed', startDate: '2026-03-10', endDate: '2026-03-12', budget: 1500, actualCost: 1350, completionPercent: 100, priority: 'medium', assignedTechnician: 'Dave Sparks', user_id: uid },
      { name: 'Moore Furnace Replacement', description: 'High-efficiency condensing furnace install', customerName: 'Patricia Moore', customerPhone: '555-0113', address: '174 Spruce Ave', projectType: 'HVAC', status: 'planning', startDate: '2026-03-26', budget: 5500, completionPercent: 0, priority: 'high', assignedTechnician: 'Carlos Ruiz', user_id: uid },
      { name: 'White Sump Pump System', description: 'Sump pump with battery backup and discharge', customerName: 'Richard White', customerPhone: '555-0114', address: '285 Cherry Lane', projectType: 'Plumbing', status: 'planning', startDate: '2026-03-26', budget: 1900, completionPercent: 0, priority: 'high', assignedTechnician: 'Mike Torres', user_id: uid },
      { name: 'Garcia Commercial Kitchen', description: 'Full commercial kitchen ventilation system', customerName: 'Maria Garcia', customerPhone: '555-0115', address: '396 Main Street', projectType: 'HVAC', status: 'in_progress', startDate: '2026-03-10', endDate: '2026-04-15', budget: 18000, actualCost: 8500, completionPercent: 45, priority: 'high', assignedTechnician: 'Marcus Johnson', user_id: uid },
      { name: 'Taylor Bathroom Renovation', description: 'Master bath plumbing and ventilation', customerName: 'Robert Taylor', customerPhone: '555-0106', address: '987 Birch Court', projectType: 'Plumbing', status: 'completed', startDate: '2026-02-20', endDate: '2026-03-05', budget: 3200, actualCost: 2950, completionPercent: 100, priority: 'medium', assignedTechnician: 'Mike Torres', user_id: uid },
    ]);
    console.log('  ✓ 15 Projects seeded');

    // 9. EXPENSES (15)
    await Expense.bulkCreate([
      { title: 'Copper Pipe Bulk Purchase', category: 'Materials', description: 'Monthly copper pipe restocking', amount: 2125.00, date: '2026-03-01', vendor: 'Ferguson Supply', receiptNumber: 'FS-20260301', paymentMethod: 'credit_card', projectName: 'General Inventory', status: 'approved', user_id: uid },
      { title: 'Work Van #1 Fuel', category: 'Fuel', description: 'March fuel for primary service van', amount: 485.00, date: '2026-03-15', vendor: 'Shell Gas Station', receiptNumber: 'SH-78234', paymentMethod: 'company_card', status: 'approved', user_id: uid },
      { title: 'Electrical Supplies Order', category: 'Materials', description: 'Wire, breakers, and outlets order', amount: 3245.00, date: '2026-03-05', vendor: 'Graybar Electric', receiptNumber: 'GB-45678', paymentMethod: 'credit_card', projectName: 'Wilson Whole House Rewire', status: 'approved', user_id: uid },
      { title: 'Business Insurance Premium', category: 'Insurance', description: 'Monthly general liability and workers comp', amount: 1850.00, date: '2026-03-01', vendor: 'State Farm', receiptNumber: 'SF-INS-0301', paymentMethod: 'bank_transfer', status: 'approved', user_id: uid },
      { title: 'Plumbing Permit Fee', category: 'Permits', description: 'Permit for Anderson sewer line repair', amount: 275.00, date: '2026-03-10', vendor: 'City of Springfield', receiptNumber: 'CSP-PLM-2234', paymentMethod: 'check', projectName: 'Anderson Sewer Replacement', status: 'approved', user_id: uid },
      { title: 'HVAC Equipment - Heat Pump', category: 'Materials', description: '3-ton heat pump for Williams project', amount: 3200.00, date: '2026-03-08', vendor: 'Carrier Wholesale', receiptNumber: 'CW-HP-9012', paymentMethod: 'credit_card', projectName: 'Williams New Construction HVAC', status: 'approved', user_id: uid },
      { title: 'Office Rent - March', category: 'Office', description: 'Monthly office/warehouse lease payment', amount: 2200.00, date: '2026-03-01', vendor: 'Springfield Properties', receiptNumber: 'SP-RENT-0326', paymentMethod: 'bank_transfer', status: 'approved', user_id: uid },
      { title: 'Tool Replacement - Pipe Wrench Set', category: 'Equipment', description: 'Replacement heavy-duty pipe wrench set', amount: 189.00, date: '2026-03-12', vendor: 'Home Depot Pro', receiptNumber: 'HDP-56789', paymentMethod: 'credit_card', isReimbursable: true, status: 'pending', user_id: uid },
      { title: 'Work Van #2 Maintenance', category: 'Equipment', description: 'Oil change and brake inspection', amount: 340.00, date: '2026-03-14', vendor: 'Jiffy Lube', receiptNumber: 'JL-34567', paymentMethod: 'company_card', status: 'approved', user_id: uid },
      { title: 'Refrigerant Supply', category: 'Materials', description: 'R-410A refrigerant cylinders (5x)', amount: 875.00, date: '2026-03-06', vendor: 'HVAC Direct', receiptNumber: 'HD-R410-5', paymentMethod: 'credit_card', projectName: 'General Inventory', status: 'approved', user_id: uid },
      { title: 'Electrical Permit - Wilson', category: 'Permits', description: 'Electrical permit for whole house rewiring', amount: 450.00, date: '2026-03-11', vendor: 'City of Springfield', receiptNumber: 'CSP-ELC-5567', paymentMethod: 'check', projectName: 'Wilson Whole House Rewire', status: 'approved', user_id: uid },
      { title: 'Safety Equipment', category: 'Equipment', description: 'Hard hats, safety glasses, gloves restock', amount: 420.00, date: '2026-03-09', vendor: 'Grainger', receiptNumber: 'GR-89012', paymentMethod: 'credit_card', status: 'approved', user_id: uid },
      { title: 'QuickBooks Subscription', category: 'Office', description: 'Monthly accounting software', amount: 85.00, date: '2026-03-01', vendor: 'Intuit', receiptNumber: 'QBO-0326', paymentMethod: 'credit_card', status: 'approved', user_id: uid },
      { title: 'Continuing Education - HVAC', category: 'Other', description: 'NATE recertification course for Carlos', amount: 350.00, date: '2026-03-07', vendor: 'HVAC Excellence', receiptNumber: 'HVACE-2026', paymentMethod: 'credit_card', isReimbursable: false, status: 'approved', user_id: uid },
      { title: 'Work Van #1 Fuel - Week 3', category: 'Fuel', description: 'Fuel for service calls week of 3/17', amount: 165.00, date: '2026-03-17', vendor: 'BP Gas Station', receiptNumber: 'BP-11234', paymentMethod: 'company_card', status: 'pending', user_id: uid },
    ]);
    console.log('  ✓ 15 Expenses seeded');

    // 10. WARRANTIES (15)
    await Warranty.bulkCreate([
      { title: 'Johnson Water Heater Warranty', customerName: 'Sarah Johnson', customerPhone: '555-0101', productName: 'A.O. Smith ProLine 50-Gal', serialNumber: 'AOS-2026-78234', warrantyType: 'manufacturer', startDate: '2026-03-20', endDate: '2032-03-20', coverage: '6-year tank warranty, 1-year parts and labor', status: 'active', user_id: uid },
      { title: 'Williams Heat Pump Warranty', customerName: 'Mike Williams', customerPhone: '555-0102', productName: 'Carrier 3-Ton Heat Pump', serialNumber: 'CAR-HP-2026-45678', warrantyType: 'manufacturer', startDate: '2026-03-28', endDate: '2036-03-28', coverage: '10-year compressor, 5-year parts', status: 'active', user_id: uid },
      { title: 'Chen Panel - Extended Warranty', customerName: 'Lisa Chen', customerPhone: '555-0103', productName: 'Square D 200A Panel', serialNumber: 'SQD-2026-12345', warrantyType: 'extended', startDate: '2026-03-21', endDate: '2031-03-21', coverage: '5-year extended coverage on panel and breakers', status: 'active', user_id: uid },
      { title: 'Brown Garbage Disposal Warranty', customerName: 'David Brown', customerPhone: '555-0104', productName: 'InSinkErator Evolution Excel', serialNumber: 'ISE-2026-67890', warrantyType: 'manufacturer', startDate: '2026-03-15', endDate: '2033-03-15', coverage: '7-year in-home full service warranty', status: 'active', user_id: uid },
      { title: 'Davis AC Compressor Warranty', customerName: 'Jennifer Davis', customerPhone: '555-0105', productName: 'Carrier AC Compressor', serialNumber: 'CAR-AC-2019-11234', warrantyType: 'manufacturer', startDate: '2019-06-15', endDate: '2029-06-15', coverage: '10-year compressor warranty', status: 'active', notes: 'Refrigerant recharge may void warranty if leak is user-caused', user_id: uid },
      { title: 'Taylor Exhaust Fan Warranty', customerName: 'Robert Taylor', customerPhone: '555-0106', productName: 'Panasonic WhisperGreen', serialNumber: 'PAN-WG-2026-22345', warrantyType: 'manufacturer', startDate: '2026-03-22', endDate: '2029-03-22', coverage: '3-year parts warranty', status: 'active', user_id: uid },
      { title: 'Wilson AFCI Breakers Warranty', customerName: 'Amanda Wilson', customerPhone: '555-0107', productName: 'Square D AFCI/GFCI Breakers (20)', serialNumber: 'SQD-AFCI-BATCH-2026', warrantyType: 'manufacturer', startDate: '2026-03-23', endDate: '2028-03-23', coverage: '2-year replacement warranty', status: 'active', user_id: uid },
      { title: 'Martinez Mini Split Warranty', customerName: 'Karen Martinez', customerPhone: '555-0109', productName: 'Mitsubishi 12K BTU Mini Split', serialNumber: 'MIT-MS-2026-33456', warrantyType: 'manufacturer', startDate: '2026-03-24', endDate: '2038-03-24', coverage: '12-year compressor, 5-year parts', status: 'active', user_id: uid },
      { title: 'Kim EV Charger Warranty', customerName: 'James Kim', customerPhone: '555-0112', productName: 'ChargePoint Home Flex', serialNumber: 'CP-HF-2026-44567', warrantyType: 'manufacturer', startDate: '2026-03-12', endDate: '2029-03-12', coverage: '3-year full unit warranty', status: 'active', user_id: uid },
      { title: 'Moore Furnace Warranty', customerName: 'Patricia Moore', customerPhone: '555-0113', productName: 'Lennox SL280V Gas Furnace', serialNumber: 'LEN-SL-2026-55678', warrantyType: 'manufacturer', startDate: '2026-03-26', endDate: '2046-03-26', coverage: '20-year heat exchanger, 5-year parts', status: 'active', user_id: uid },
      { title: 'White Sump Pump Warranty', customerName: 'Richard White', customerPhone: '555-0114', productName: 'Zoeller M53 Sump Pump', serialNumber: 'ZOE-M53-2026-66789', warrantyType: 'manufacturer', startDate: '2026-03-26', endDate: '2029-03-26', coverage: '3-year warranty on motor and housing', status: 'active', user_id: uid },
      { title: 'Garcia Hood System Warranty', customerName: 'Maria Garcia', customerPhone: '555-0115', productName: 'CaptiveAire Type I Hood', serialNumber: 'CA-TI-2026-77890', warrantyType: 'manufacturer', startDate: '2026-04-15', endDate: '2031-04-15', coverage: '5-year hood body, 2-year fan motor', status: 'active', user_id: uid },
      { title: 'Robinson Lighting Transformer', customerName: 'Steve Robinson', customerPhone: '555-0110', productName: 'Kichler 600W Transformer', serialNumber: 'KCH-600-2026-88901', warrantyType: 'manufacturer', startDate: '2026-03-24', endDate: '2041-03-24', coverage: '15-year warranty on transformer', status: 'active', user_id: uid },
      { title: 'Lee Gas Valve - Labor Warranty', customerName: 'Nancy Lee', customerPhone: '555-0111', productName: 'ProTrades Labor Warranty', serialNumber: 'PT-LAB-2026-001', warrantyType: 'labor', startDate: '2026-03-25', endDate: '2027-03-25', coverage: '1-year labor warranty on gas line installation', status: 'active', user_id: uid },
      { title: 'Anderson PVC Pipe - Labor', customerName: 'Thomas Anderson', customerPhone: '555-0108', productName: 'ProTrades Labor Warranty', serialNumber: 'PT-LAB-2026-002', warrantyType: 'labor', startDate: '2026-03-23', endDate: '2027-03-23', coverage: '1-year labor warranty on sewer line replacement', status: 'active', user_id: uid },
    ]);
    console.log('  ✓ 15 Warranties seeded');

    // 11. EQUIPMENT (15)
    await Equipment.bulkCreate([
      { name: 'Service Van #1 - Ford Transit', category: 'Vehicles', description: '2023 Ford Transit 250 cargo van', serialNumber: 'VIN-1FTBR1C84MKA12345', purchaseDate: '2023-01-15', purchaseCost: 42000, currentValue: 35000, condition: 'good', location: 'Main Yard', assignedTo: 'Mike Torres', status: 'in_use', nextMaintenanceDate: '2026-04-15', user_id: uid },
      { name: 'Service Van #2 - Chevy Express', category: 'Vehicles', description: '2022 Chevy Express 2500', serialNumber: 'VIN-1GCWGAFP8N1234567', purchaseDate: '2022-06-20', purchaseCost: 38000, currentValue: 28000, condition: 'good', location: 'Main Yard', assignedTo: 'Carlos Ruiz', status: 'in_use', nextMaintenanceDate: '2026-04-01', user_id: uid },
      { name: 'Milwaukee M18 Drill Kit', category: 'Tools', description: 'Cordless drill/driver combo with 2 batteries', serialNumber: 'MIL-M18-78901', purchaseDate: '2024-08-10', purchaseCost: 299, currentValue: 200, condition: 'good', location: 'Van #1', assignedTo: 'Mike Torres', status: 'in_use', user_id: uid },
      { name: 'RIDGID SeeSnake Camera', category: 'Diagnostic', description: 'Sewer inspection camera system', serialNumber: 'RDG-SS-45678', purchaseDate: '2023-05-01', purchaseCost: 5800, currentValue: 4200, condition: 'excellent', location: 'Warehouse', status: 'available', nextMaintenanceDate: '2026-06-01', user_id: uid },
      { name: 'Fluke 117 Multimeter', category: 'Diagnostic', description: 'True-RMS digital multimeter', serialNumber: 'FLK-117-23456', purchaseDate: '2024-02-14', purchaseCost: 189, currentValue: 150, condition: 'good', location: 'Van #3', assignedTo: 'Dave Sparks', status: 'in_use', user_id: uid },
      { name: 'Fieldpiece SMAN360 Manifold', category: 'Diagnostic', description: '3-port digital manifold with hoses', serialNumber: 'FP-SM360-34567', purchaseDate: '2024-06-15', purchaseCost: 450, currentValue: 380, condition: 'excellent', location: 'Van #2', assignedTo: 'Carlos Ruiz', status: 'in_use', user_id: uid },
      { name: 'Hilti TE 30-A36 Rotary Hammer', category: 'Tools', description: 'Cordless rotary hammer drill', serialNumber: 'HLT-TE30-56789', purchaseDate: '2023-11-20', purchaseCost: 899, currentValue: 650, condition: 'good', location: 'Warehouse', status: 'available', user_id: uid },
      { name: 'Klein Tools Journeyman Kit', category: 'Tools', description: 'Complete electrician hand tool set', serialNumber: 'KLN-JRN-67890', purchaseDate: '2024-01-10', purchaseCost: 350, currentValue: 280, condition: 'good', location: 'Van #3', assignedTo: 'Dave Sparks', status: 'in_use', user_id: uid },
      { name: 'Yellow Jacket Vacuum Pump', category: 'Tools', description: '7 CFM two-stage vacuum pump for HVAC', serialNumber: 'YJ-VP7-78901', purchaseDate: '2023-09-05', purchaseCost: 420, currentValue: 320, condition: 'good', location: 'Van #2', assignedTo: 'Carlos Ruiz', status: 'in_use', user_id: uid },
      { name: 'RIDGID 300 Threading Machine', category: 'Heavy Equipment', description: 'Power pipe threading machine', serialNumber: 'RDG-300-89012', purchaseDate: '2022-03-15', purchaseCost: 3200, currentValue: 2400, condition: 'fair', location: 'Warehouse', status: 'available', nextMaintenanceDate: '2026-05-01', notes: 'Needs die replacement soon', user_id: uid },
      { name: 'Fire Extinguisher Set (5)', category: 'Safety', description: 'ABC fire extinguishers for vans', serialNumber: 'FE-SET-2024-01', purchaseDate: '2024-06-01', purchaseCost: 250, currentValue: 200, condition: 'good', location: 'All Vans', status: 'in_use', nextMaintenanceDate: '2026-06-01', user_id: uid },
      { name: 'Confined Space Entry Kit', category: 'Safety', description: 'Tripod, harness, and gas detector', serialNumber: 'CSE-KIT-90123', purchaseDate: '2023-07-20', purchaseCost: 1800, currentValue: 1400, condition: 'good', location: 'Warehouse', status: 'available', nextMaintenanceDate: '2026-07-20', user_id: uid },
      { name: 'Service Van #3 - RAM ProMaster', category: 'Vehicles', description: '2024 RAM ProMaster 1500', serialNumber: 'VIN-3C6LRVAG4RE123456', purchaseDate: '2024-03-01', purchaseCost: 40000, currentValue: 36000, condition: 'excellent', location: 'Main Yard', assignedTo: 'Dave Sparks', status: 'in_use', nextMaintenanceDate: '2026-05-01', user_id: uid },
      { name: 'FLIR C5 Thermal Camera', category: 'Diagnostic', description: 'Compact thermal imaging camera', serialNumber: 'FLIR-C5-01234', purchaseDate: '2024-11-10', purchaseCost: 700, currentValue: 600, condition: 'excellent', location: 'Office', status: 'available', user_id: uid },
      { name: 'Generac 7500W Generator', category: 'Heavy Equipment', description: 'Portable generator for job sites', serialNumber: 'GEN-7500-12345', purchaseDate: '2023-02-28', purchaseCost: 1100, currentValue: 850, condition: 'good', location: 'Warehouse', status: 'available', nextMaintenanceDate: '2026-04-30', user_id: uid },
    ]);
    console.log('  ✓ 15 Equipment items seeded');

    // 12. SERVICE CONTRACTS (15)
    await ServiceContract.bulkCreate([
      { contractNumber: 'SC-2026-001', customerName: 'David Brown', customerEmail: 'david@email.com', customerPhone: '555-0104', serviceType: 'Plumbing', description: 'Annual plumbing maintenance - drain cleaning, water heater flush, fixture inspection', startDate: '2026-01-01', endDate: '2026-12-31', monthlyFee: 49.99, annualValue: 599.88, visitsIncluded: 2, visitsUsed: 0, status: 'active', renewalDate: '2026-12-01', user_id: uid },
      { contractNumber: 'SC-2026-002', customerName: 'Jennifer Davis', customerEmail: 'jen@email.com', customerPhone: '555-0105', serviceType: 'HVAC', description: 'Premium HVAC maintenance - biannual tune-ups, filter changes, priority service', startDate: '2026-01-01', endDate: '2026-12-31', monthlyFee: 79.99, annualValue: 959.88, visitsIncluded: 4, visitsUsed: 1, status: 'active', renewalDate: '2026-12-01', user_id: uid },
      { contractNumber: 'SC-2026-003', customerName: 'Maria Garcia', customerEmail: 'maria@email.com', customerPhone: '555-0115', serviceType: 'Comprehensive', description: 'Commercial kitchen - monthly hood cleaning, quarterly HVAC service, emergency plumbing', startDate: '2026-01-01', endDate: '2026-12-31', monthlyFee: 299.99, annualValue: 3599.88, visitsIncluded: 12, visitsUsed: 3, status: 'active', renewalDate: '2026-12-01', user_id: uid },
      { contractNumber: 'SC-2026-004', customerName: 'Amanda Wilson', customerEmail: 'amanda@email.com', customerPhone: '555-0107', serviceType: 'Electrical', description: 'Annual electrical safety inspection and smoke detector testing', startDate: '2026-01-01', endDate: '2026-12-31', monthlyFee: 29.99, annualValue: 359.88, visitsIncluded: 1, visitsUsed: 0, status: 'active', renewalDate: '2026-12-01', user_id: uid },
      { contractNumber: 'SC-2026-005', customerName: 'Karen Martinez', customerEmail: 'karen@email.com', customerPhone: '555-0109', serviceType: 'HVAC', description: 'Mini-split maintenance - annual cleaning and refrigerant check', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 39.99, annualValue: 479.88, visitsIncluded: 2, visitsUsed: 0, status: 'pending', renewalDate: '2027-03-01', user_id: uid },
      { contractNumber: 'SC-2025-006', customerName: 'Robert Taylor', customerEmail: 'rob@email.com', customerPhone: '555-0106', serviceType: 'Plumbing', description: 'Basic plumbing checkup - annual inspection', startDate: '2025-01-01', endDate: '2025-12-31', monthlyFee: 24.99, annualValue: 299.88, visitsIncluded: 1, visitsUsed: 1, status: 'expired', renewalDate: '2025-12-01', notes: 'Contact for renewal', user_id: uid },
      { contractNumber: 'SC-2026-007', customerName: 'Steve Robinson', customerEmail: 'steve@email.com', customerPhone: '555-0110', serviceType: 'Electrical', description: 'Landscape lighting annual service - bulb replacement and timer adjustment', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 19.99, annualValue: 239.88, visitsIncluded: 2, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2026-008', customerName: 'Patricia Moore', customerEmail: 'pat@email.com', customerPhone: '555-0113', serviceType: 'HVAC', description: 'Furnace and AC maintenance plan with priority emergency service', startDate: '2026-01-01', endDate: '2026-12-31', monthlyFee: 69.99, annualValue: 839.88, visitsIncluded: 4, visitsUsed: 1, status: 'active', renewalDate: '2026-12-01', user_id: uid },
      { contractNumber: 'SC-2026-009', customerName: 'Richard White', customerEmail: 'rich@email.com', customerPhone: '555-0114', serviceType: 'Plumbing', description: 'Sump pump annual testing and battery backup check', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 19.99, annualValue: 239.88, visitsIncluded: 1, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2026-010', customerName: 'Thomas Anderson', customerEmail: 'tom@email.com', customerPhone: '555-0108', serviceType: 'Plumbing', description: 'New sewer line maintenance - annual camera inspection', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 29.99, annualValue: 359.88, visitsIncluded: 1, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2026-011', customerName: 'Sarah Johnson', customerEmail: 'sarah@email.com', customerPhone: '555-0101', serviceType: 'Plumbing', description: 'Water heater maintenance plan - annual flush and anode rod check', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 14.99, annualValue: 179.88, visitsIncluded: 1, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2026-012', customerName: 'Mike Williams', customerEmail: 'mike@email.com', customerPhone: '555-0102', serviceType: 'Comprehensive', description: 'New home warranty service plan - HVAC, electrical, plumbing coverage', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 149.99, annualValue: 1799.88, visitsIncluded: 6, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2026-013', customerName: 'Lisa Chen', customerEmail: 'lisa@email.com', customerPhone: '555-0103', serviceType: 'Electrical', description: 'Annual electrical panel inspection and thermal scan', startDate: '2026-04-01', endDate: '2027-03-31', monthlyFee: 34.99, annualValue: 419.88, visitsIncluded: 1, visitsUsed: 0, status: 'pending', user_id: uid },
      { contractNumber: 'SC-2025-014', customerName: 'James Kim', customerEmail: 'james@email.com', customerPhone: '555-0112', serviceType: 'Electrical', description: 'EV charger annual inspection and firmware update', startDate: '2025-04-01', endDate: '2026-03-31', monthlyFee: 14.99, annualValue: 179.88, visitsIncluded: 1, visitsUsed: 1, status: 'active', renewalDate: '2026-03-01', user_id: uid },
      { contractNumber: 'SC-2025-015', customerName: 'Nancy Lee', customerEmail: 'nancy@email.com', customerPhone: '555-0111', serviceType: 'Plumbing', description: 'Gas line annual leak inspection', startDate: '2025-06-01', endDate: '2026-05-31', monthlyFee: 19.99, annualValue: 239.88, visitsIncluded: 1, visitsUsed: 0, status: 'cancelled', notes: 'Customer requested cancellation due to payment issues', user_id: uid },
    ]);
    console.log('  ✓ 15 Service Contracts seeded');

    // 13. PERMITS (15)
    await Permit.bulkCreate([
      { permitNumber: 'PLM-2026-001', title: 'Water Heater Replacement Permit', permitType: 'Plumbing', projectAddress: '123 Oak Street', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-15', issueDate: '2026-03-18', expirationDate: '2026-09-18', fee: 125, status: 'issued', inspectionDate: '2026-03-20', notes: 'Same-day inspection requested', user_id: uid },
      { permitNumber: 'MEC-2026-001', title: 'HVAC System Installation', permitType: 'Mechanical', projectAddress: '456 Maple Ave', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-01', issueDate: '2026-03-10', expirationDate: '2026-09-10', fee: 350, status: 'issued', notes: 'New construction - multiple inspections required', user_id: uid },
      { permitNumber: 'ELC-2026-001', title: '200A Panel Upgrade Permit', permitType: 'Electrical', projectAddress: '789 Elm Drive', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-12', issueDate: '2026-03-19', expirationDate: '2026-09-19', fee: 200, status: 'issued', user_id: uid },
      { permitNumber: 'PLM-2026-002', title: 'Kitchen Plumbing Remodel', permitType: 'Plumbing', projectAddress: '321 Pine Road', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-05', issueDate: '2026-03-08', expirationDate: '2026-09-08', fee: 150, status: 'issued', inspectionDate: '2026-03-22', inspectionResult: 'Pending', user_id: uid },
      { permitNumber: 'ELC-2026-002', title: 'Whole House Rewiring Permit', permitType: 'Electrical', projectAddress: '147 Willow Way', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-10', issueDate: '2026-03-17', expirationDate: '2026-09-17', fee: 450, status: 'issued', notes: 'Multiple rough-in inspections needed', user_id: uid },
      { permitNumber: 'PLM-2026-003', title: 'Sewer Line Replacement', permitType: 'Plumbing', projectAddress: '258 Ash Blvd', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-11', issueDate: '2026-03-18', expirationDate: '2026-09-18', fee: 275, status: 'issued', notes: 'ROW permit also required', user_id: uid },
      { permitNumber: 'MEC-2026-002', title: 'Mini Split Installation', permitType: 'Mechanical', projectAddress: '369 Poplar Place', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-15', expirationDate: '2026-09-20', fee: 125, status: 'pending', notes: 'Awaiting review', user_id: uid },
      { permitNumber: 'ELC-2026-003', title: 'Landscape Lighting Permit', permitType: 'Electrical', projectAddress: '741 Magnolia Dr', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-14', issueDate: '2026-03-19', expirationDate: '2026-09-19', fee: 100, status: 'issued', user_id: uid },
      { permitNumber: 'PLM-2026-004', title: 'Gas Line Installation', permitType: 'Plumbing', projectAddress: '852 Walnut Circle', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-16', fee: 175, status: 'pending', notes: 'Gas company coordination needed', user_id: uid },
      { permitNumber: 'ELC-2026-004', title: 'EV Charger Circuit Permit', permitType: 'Electrical', projectAddress: '963 Hickory St', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-05', issueDate: '2026-03-08', expirationDate: '2026-09-08', fee: 100, status: 'issued', inspectionDate: '2026-03-12', inspectionResult: 'Passed', user_id: uid },
      { permitNumber: 'MEC-2026-003', title: 'Furnace Replacement Permit', permitType: 'Mechanical', projectAddress: '174 Spruce Ave', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-17', fee: 175, status: 'pending', user_id: uid },
      { permitNumber: 'PLM-2026-005', title: 'Sump Pump Installation', permitType: 'Plumbing', projectAddress: '285 Cherry Lane', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-17', fee: 100, status: 'pending', notes: 'Expedited review requested', user_id: uid },
      { permitNumber: 'FIR-2026-001', title: 'Commercial Kitchen Hood - Fire', permitType: 'Fire', projectAddress: '396 Main Street', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'Springfield Fire Marshal', applicationDate: '2026-03-01', issueDate: '2026-03-12', expirationDate: '2026-09-12', fee: 500, status: 'issued', notes: 'Fire suppression system requires separate UL listing', user_id: uid },
      { permitNumber: 'MEC-2026-004', title: 'Commercial Kitchen Ventilation', permitType: 'Mechanical', projectAddress: '396 Main Street', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-03-01', issueDate: '2026-03-10', expirationDate: '2026-09-10', fee: 400, status: 'issued', user_id: uid },
      { permitNumber: 'BLD-2026-001', title: 'Williams New Construction - General', permitType: 'Building', projectAddress: '456 Maple Ave', applicantName: 'ProTrades HVAC & Plumbing', issuingAuthority: 'City of Springfield Building Dept', applicationDate: '2026-02-15', issueDate: '2026-02-28', expirationDate: '2027-02-28', fee: 800, status: 'issued', notes: 'Master permit for new construction', user_id: uid },
    ]);
    console.log('  ✓ 15 Permits seeded');

    // 14. SUPPLIERS (15)
    await Supplier.bulkCreate([
      { name: 'Ferguson Supply', contactPerson: 'Mark Stevens', email: 'orders@ferguson.com', phone: '555-8001', address: '1000 Industrial Blvd, Springfield, IL', website: 'ferguson.com', category: 'Plumbing', accountNumber: 'FERG-PRO-2024', paymentTerms: 'Net 30', rating: 5, leadTimeDays: 1, minimumOrder: 50, status: 'preferred', notes: 'Primary plumbing supplier - excellent stock', user_id: uid },
      { name: 'Graybar Electric', contactPerson: 'Susan Park', email: 'orders@graybar.com', phone: '555-8002', address: '2000 Commerce Way, Springfield, IL', website: 'graybar.com', category: 'Electrical', accountNumber: 'GRAY-PRO-2024', paymentTerms: 'Net 30', rating: 5, leadTimeDays: 1, minimumOrder: 75, status: 'preferred', notes: 'Primary electrical supplier', user_id: uid },
      { name: 'HVAC Direct', contactPerson: 'Tony Martinez', email: 'sales@hvacdirect.com', phone: '555-8003', address: '3000 Air Park Rd, Springfield, IL', website: 'hvacdirect.com', category: 'HVAC', accountNumber: 'HVCD-PRO-2024', paymentTerms: 'Net 30', rating: 4, leadTimeDays: 2, minimumOrder: 100, status: 'preferred', user_id: uid },
      { name: 'Carrier Wholesale', contactPerson: 'Bill Thompson', email: 'wholesale@carrier.com', phone: '555-8004', address: '4000 Carrier Pkwy, Indianapolis, IN', website: 'carrier.com', category: 'HVAC', accountNumber: 'CARR-DLR-2024', paymentTerms: 'Net 45', rating: 5, leadTimeDays: 5, minimumOrder: 500, status: 'active', notes: 'Authorized Carrier dealer', user_id: uid },
      { name: 'Home Depot Pro', contactPerson: 'Web Orders', email: 'pro@homedepot.com', phone: '555-8005', address: '5000 Retail Way, Springfield, IL', website: 'homedepot.com/pro', category: 'General', accountNumber: 'HDP-PRO-2024', paymentTerms: 'Net 15', rating: 3, leadTimeDays: 1, minimumOrder: 0, status: 'active', notes: 'Emergency/same-day orders only', user_id: uid },
      { name: 'Grainger', contactPerson: 'Order Desk', email: 'orders@grainger.com', phone: '555-8006', address: '6000 Supply Chain Dr, Springfield, IL', website: 'grainger.com', category: 'General', accountNumber: 'GRG-PRO-2024', paymentTerms: 'Net 30', rating: 4, leadTimeDays: 1, minimumOrder: 25, status: 'active', notes: 'Safety equipment and MRO supplies', user_id: uid },
      { name: 'Lennox Distributor', contactPerson: 'Kim Watson', email: 'dist@lennox.com', phone: '555-8007', address: '7000 HVAC Blvd, St Louis, MO', website: 'lennox.com', category: 'HVAC', accountNumber: 'LEN-DLR-2024', paymentTerms: 'Net 45', rating: 4, leadTimeDays: 5, minimumOrder: 500, status: 'active', user_id: uid },
      { name: 'Milwaukee Tool Direct', contactPerson: 'Sales Team', email: 'sales@milwaukeetool.com', phone: '555-8008', address: 'Online Orders', website: 'milwaukeetool.com', category: 'General', accountNumber: 'MIL-PRO-2024', paymentTerms: 'Prepaid', rating: 5, leadTimeDays: 3, minimumOrder: 0, status: 'active', notes: 'Power tools and accessories', user_id: uid },
      { name: 'Johnstone Supply', contactPerson: 'Dave Morris', email: 'orders@johnstonesupply.com', phone: '555-8009', address: '8000 Wholesale Ave, Springfield, IL', website: 'johnstonesupply.com', category: 'HVAC', accountNumber: 'JOHN-PRO-2024', paymentTerms: 'Net 30', rating: 4, leadTimeDays: 1, minimumOrder: 50, status: 'active', user_id: uid },
      { name: 'Watts Water Technologies', contactPerson: 'Order Dept', email: 'orders@watts.com', phone: '555-8010', address: 'Online Orders', website: 'watts.com', category: 'Plumbing', accountNumber: 'WAT-PRO-2024', paymentTerms: 'Net 30', rating: 4, leadTimeDays: 3, minimumOrder: 100, status: 'active', notes: 'Backflow preventers and water products', user_id: uid },
      { name: 'Eaton Electrical', contactPerson: 'Sales Desk', email: 'sales@eaton.com', phone: '555-8011', address: 'Online Orders', website: 'eaton.com', category: 'Electrical', accountNumber: 'EAT-PRO-2024', paymentTerms: 'Net 30', rating: 4, leadTimeDays: 3, minimumOrder: 200, status: 'active', user_id: uid },
      { name: 'RIDGID Professional', contactPerson: 'Pro Sales', email: 'prosales@ridgid.com', phone: '555-8012', address: 'Online Orders', website: 'ridgid.com', category: 'General', accountNumber: 'RDG-PRO-2024', paymentTerms: 'Prepaid', rating: 5, leadTimeDays: 5, minimumOrder: 0, status: 'active', notes: 'Plumbing tools and equipment', user_id: uid },
      { name: 'Springfield Plumbing Supply', contactPerson: 'Joe Franklin', email: 'joe@springfieldplumbing.com', phone: '555-8013', address: '9000 Local Trade Rd, Springfield, IL', category: 'Plumbing', paymentTerms: 'COD', rating: 3, leadTimeDays: 0, minimumOrder: 0, status: 'active', notes: 'Local supplier - good for emergency same-day needs', user_id: uid },
      { name: 'CaptiveAire Systems', contactPerson: 'Commercial Sales', email: 'sales@captiveaire.com', phone: '555-8014', address: 'Online Orders', website: 'captiveaire.com', category: 'HVAC', accountNumber: 'CAP-DLR-2024', paymentTerms: 'Net 60', rating: 5, leadTimeDays: 14, minimumOrder: 1000, status: 'active', notes: 'Commercial kitchen ventilation specialist', user_id: uid },
      { name: 'Klein Tools', contactPerson: 'Distributor Portal', email: 'orders@kleintools.com', phone: '555-8015', address: 'Online Orders', website: 'kleintools.com', category: 'Electrical', accountNumber: 'KLN-PRO-2024', paymentTerms: 'Prepaid', rating: 5, leadTimeDays: 3, minimumOrder: 0, status: 'active', notes: 'Electrician hand tools', user_id: uid },
    ]);
    console.log('  ✓ 15 Suppliers seeded');

    console.log('\n✅ Database seeded successfully! (15 features × 15 items = 225 records)');
    console.log('  Demo Login: demo@hvacpro.com / password123\n');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
